services:
  showcase.codechovui.dev:
    build: .
    container_name: showcase.codechovui.dev
    hostname: showcase.codechovui.dev
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - ./data:/app/data
      - ./media:/app/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.showcase-codechovui.rule=Host(`showcase.codechovui.dev`)"
      - "traefik.http.routers.showcase-codechovui.entrypoints=websecure"
      - "traefik.http.routers.showcase-codechovui.tls.certresolver=myresolver"
      - "traefik.http.services.showcase-codechovui.loadbalancer.server.port=3000"
    networks:
      - traefik_default
    restart: unless-stopped

networks:
  traefik_default:
    external: true